name: petpath
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase_messaging: ^4.0.0+1
  
  flutter:
    sdk: flutter

 
  cupertino_icons: ^0.1.2
  provider: 2.0.1
  google_maps_flutter: ^0.4.0
  font_awesome_flutter: ^8.2.0 
  charts_flutter: ^0.6.0
  flutter_screenutil: ^0.4.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
firebase_core: ^0.4.0+9
firebase_analytics: ^5.0.2
firebase_auth: ^0.14.0+5
cloud_firestore: ^0.12.9+5



flutter:

 
  uses-material-design: true

  assets:
    - assets/flutter-icon.png